from webfluid.core.freeze import Freezable

class StaticPrefixes(Freezable):
    label: str
    closed_after: str
    _prefixes: set[str]
    def __init__(self, *prefixes: str) -> None: ...
    def add(self, prefix: str) -> None: ...
    def freeze(self, value: tuple[str, ...] | None = None) -> tuple[str, ...]: ...
    def matches(self, path: str) -> bool: ...
