class StaticPrefixes:
    _prefixes: set[str]
    _frozen: tuple[str, ...] | None
    def __init__(self, *prefixes: str) -> None: ...
    def add(self, prefix: str) -> None: ...
    def freeze(self) -> None: ...
    def matches(self, path: str) -> bool: ...
