from jinja2 import PrefixLoader

from webfluid.core.additive.main import Additive
from webfluid.core.additive.manifest import Manifest
from webfluid.core.additive.router import Router
from webfluid.surface.frontend import Frontend

class BaseKind:
    is_base: bool
    def routers(self) -> tuple[Router, Router, Router]: ...
    def frontend(self) -> None: ...
    def loader(self, additive: Additive) -> None: ...
    def check_enable(self, additive: Additive) -> None: ...

class FeatureKind:
    is_base: bool
    def routers(self) -> tuple[Router, Router, Router]: ...
    def frontend(self) -> Frontend: ...
    def loader(self, additive: Additive) -> PrefixLoader: ...
    def check_enable(self, additive: Additive) -> None: ...

def kind_for(manifest: Manifest) -> BaseKind | FeatureKind: ...
