from collections.abc import Callable, ItemsView, KeysView, ValuesView
from pathlib import Path
from typing import Any

class Manifest:
    structure: dict[str, tuple[type, bool] | tuple[type, bool, Callable[[Any], tuple[bool, Any]]]]
    _data: dict[str, Any]
    def __init__(self, manifest_file: Path) -> None: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, item: str) -> bool: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def items(self) -> ItemsView[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def pop(self, key: str, default: Any = None) -> Any: ...
    def check_requirements(self, additive_root: Path) -> None: ...
    @classmethod
    def validated_data(cls, target: dict[str, Any]) -> dict[str, Any]: ...
