from pathlib import Path
from typing import Any

from webfluid.core.additive.manifest import Manifest

def normalize(requirement: list[str] | dict[str, str], name: str) -> dict[str, str]: ...

class RequirementChecker:
    manifest: Manifest
    additive_root: Path
    name: str
    def __init__(self, manifest: Manifest, additive_root: Path) -> None: ...
    def check(self) -> None: ...
    def _check_framework(self, requirements: dict[str, Any]) -> None: ...
    def _check_additives(self, requirement: list[str] | dict[str, str]) -> None: ...
