from fastapi import Request
from markupsafe import Markup

from webfluid import Fluid

class Themes:
    themes: dict[str, Markup]
    global_theme: str
    def __init__(self, fluid: Fluid) -> None: ...
    def _validate(self, name: str, exists: bool) -> None: ...
    def add(self, name: str, link: Markup) -> None: ...
    def get(self) -> Markup: ...
    def set(self, request: Request, name: str) -> None: ...
