[project]
name = "webfluid"
version = "1.0.0a2"
description = "A cli first fullstack framework for fast and easy web development."
authors = [
    { name = "Pierre", email = "pierre@growv-mail.org" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "jinja2",
    "babel",

    "sqlalchemy",
    "psycopg[binary]",
    "pymysql",
    "aiomysql",
    "aiosqlite",
    "redis>=7.3.0",
    "alembic",

    "uvicorn",
    "asgiref",
    "requests",
    "httpx",
    "websockets",
    "slowapi>=0.1.9",
    "limits>=5.8.0",
    "packaging>=26.0",
    "python-multipart",
    "apscheduler",
    "aiosmtplib",
    "gitpython",
    "frozendict",
    "selectolax",
    "pytz",

    "argon2_cffi",
    "itsdangerous",
    "pyjwt",

    "typer",
    "tqdm",
    "questionary"
]

[project.scripts]
wf = "webfluid.cli:cli"

[project.entry-points."webfluid.extensions"]
babel = "webfluid.extensions.babel:Babel"
migrate = "webfluid.extensions.migrate:Migrate"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
webfluid = [
    "extensions/babel/babel.cfg",
    "fluid/templates/**/*.html",
    "fluid/static/**/*"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--disable-warnings"