from pathlib import Path
from typing import Any
import subprocess

import typer

def _sys_node() -> tuple[bool, str]: ...
def _get_node_data() -> tuple[str, str]: ...
def _node_cmd(cmd: str) -> str: ...
def _node_env() -> dict[str, str]: ...
def node_cmd(cmd: list[str], cwd: Path | str = ..., **kwargs: Any) -> None: ...
def node_proc(
    cmd: list[str], cwd: Path | str = ..., **kwargs: Any
) -> subprocess.Popen[Any]: ...
def load_node() -> None: ...
def node(ctx: typer.Context) -> None: ...
def cli_entry(app: typer.Typer) -> None: ...
