from collections.abc import Callable
from pathlib import Path
from typing import Any

import typer

from webfluid import Fluid

def _get_cli_data() -> tuple[str, str]: ...
def _tailwind_cmd() -> str: ...
def tailwind_cmd(args: list[str], cwd: Path | str = ..., **kwargs: Any) -> None: ...
def generate_asset(in_file: Path, out_file: Path, cwd: Path) -> None: ...
def generate_tailwind_css(fluid: Fluid) -> None: ...
def load_tailwind(download_fn: Callable[..., Any]) -> None: ...
def tailwind(ctx: typer.Context) -> None: ...
def cli_entry(app: typer.Typer) -> None: ...
