from typing import Any

from webfluid.extensions.jwt.config import JWTConfig

class Decoder:
    _config: JWTConfig
    def __init__(self, config: JWTConfig) -> None: ...
    def _payload(self, token: str, audience: str, secret: str) -> dict[str, Any]: ...
    def _kid(self, token: str) -> str | None: ...
    def decode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
    async def adecode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
