from typing import Any

from webfluid.extensions.jwt.main import JWTManager

class Decoder:
    _jwt_manager: JWTManager
    def __init__(self, jwt_manager: JWTManager) -> None: ...
    def _decode(
        self, token: str, audience: str, secret: str, cache: Any
    ) -> dict[str, Any]: ...
    def decode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
    async def adecode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
