from webfluid import Fluid
from webfluid.extensions.jwt.main import JWTManager

async def _rotate_secret(jwt_manager: JWTManager) -> None: ...
def add_job(fluid: Fluid, jwt_manager: JWTManager) -> None: ...
