from collections.abc import Callable
from pathlib import Path
from typing import Any

from webfluid import Fluid, Additive

_additives: dict[str, dict[Path, list[tuple[str, str, str]]]]

def _load_additives(
    package: Path, target: str, additive_type: str, do_log: bool
) -> None: ...
def installed_additives(
    package: Path, do_log: bool = False, cache: bool = True
) -> list[tuple[str, str, str]]: ...
def installed_bases(
    package: Path, do_log: bool = False, cache: bool = True
) -> list[tuple[str, str, str]]: ...
def import_base(base_id: str) -> Additive | None: ...
def id_check(additive_id: str) -> tuple[bool, str]: ...
def version_check(v: str) -> tuple[bool, str]: ...
def type_check(t: str) -> tuple[bool, str]: ...
def require_extensions(
    *extensions: str
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
async def register_additives(fluid: Fluid) -> None: ...
