from collections.abc import Callable
from types import ModuleType
from typing import Any

import httpx

from webfluid import Fluid, Additive, AdditiveVersion

_stage_map: dict[str, int]
_proxy_client: httpx.AsyncClient

def enabled(key: str) -> bool: ...
def random_code(length: int = 6) -> str: ...
def safe_string(text: str) -> str: ...
def camel_to_snake(text: str) -> str: ...
def final_version(v_str: str) -> tuple[int, str, int]: ...
def get_root_path(import_name: str) -> str: ...
def parse_config(key: str, value: str) -> tuple[str, str]: ...
def required_arg_count(fn: Callable[..., Any]) -> int: ...
def is_async_function(fn: Callable[..., Any]) -> bool: ...
async def async_result(result: Any) -> Any: ...
async def safe_execute(
    fn: Callable[..., Any], reraise: bool, *args: Any, **kwargs: Any
) -> Any: ...
async def run_in_executor(
    fn: Callable[..., Any], *args: Any, executor: Any = None
) -> Any: ...
def check_priority(priority: int) -> None: ...
def build_sorted_tuple(
    data: dict[int, Any], defaults: tuple[Any, ...] | None = None
) -> tuple[Any, ...]: ...
def try_import(name: str) -> ModuleType | None: ...
def check_required_version(
    requirement: str, version_type: str = "wf",
    additive_version: AdditiveVersion | str | None = None
) -> bool: ...
def get_proxy(
    base_url: str, prefix: str = "", pass_prefix: bool = False,
    proxy_plugin: Callable[..., Any] | None = None
) -> Callable[..., Any]: ...
def get_websocket_proxy(
    base_url: str, prefix: str = "", pass_prefix: bool = False,
    proxy_plugin: Callable[..., Any] | None = None
) -> Callable[..., Any]: ...
def add_proxy(
    target: Fluid | Additive, base_url: str, prefix: str = "",
    pass_prefix: bool = False, proxy_plugin: Callable[..., Any] | None = None
) -> None: ...
async def close_proxy_client() -> None: ...
