from enum import StrEnum

from babel import Locale
from fastapi import Request

DEFAULT_COUNTRY: str
ISO_3166_1_ALPHA2: tuple[str, ...]
_CODE_SET: frozenset[str]
Country: type[StrEnum]
_GEO_HEADERS: tuple[str, ...]
_GEO_IGNORED: frozenset[str]

def is_valid(code: str | None) -> bool: ...
def coerce(code: str | None) -> StrEnum: ...
def normalize(code: str | None) -> str | None: ...
def localized_names(locale: Locale | str | None = None) -> dict[str, str]: ...
def options(locale: Locale | str | None = None) -> list[dict[str, str]]: ...
def country_from_request(
    request: Request | None = None, fallback: str = ...
) -> str: ...
