import logging
from collections.abc import Callable
from contextvars import ContextVar
from typing import Any

from webfluid.core.context import BaseContext

class _LogContext(BaseContext):
    _ctx: ContextVar[_LogContext]
    logger: str
    def __init__(self, logger_name: str) -> None: ...

class _Formatter(logging.Formatter):
    FORMATS: dict[int, dict[str, Any]]
    simple_formatter: logging.Formatter
    def __init__(self) -> None: ...
    def format(self, record: logging.LogRecord) -> str: ...

class _ColoredStreamHandler(logging.StreamHandler[Any]):
    def emit(self, record: logging.LogRecord) -> None: ...

class LogFactory:
    formatter: _Formatter
    colored_console: _ColoredStreamHandler
    console: logging.StreamHandler[Any]
    main_logger: str
    adtv_logger: str
    def __init__(self) -> None: ...
    def additive_context(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def log(self, message: str, category: int = ...) -> None: ...
    def debug(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def critical(self, message: str) -> None: ...
    def exception(self, exc: Exception, message: str | None = None) -> None: ...
    def start_session(self) -> None: ...
    @property
    def logger(self) -> logging.Logger: ...

factory: LogFactory
