from pathlib import Path
from typing import Any

import httpx

TOKEN_FILE: Path
ERROR_MESSAGES: dict[str, str]

def humanize_error(detail: str | None, fallback: str | None = None) -> str: ...
def token_file() -> Path: ...
def load_token() -> str | None: ...
def save_token(token: str) -> None: ...
def delete_token() -> bool: ...
def extract_archive(data: bytes, target: Path) -> None: ...

class Ocean:
    base_url: str
    auth_url: str
    token: str | None
    def __init__(
        self, token: str | None = None, base_url: str = ..., auth_url: str = ...
    ) -> None: ...
    @property
    def authenticated(self) -> bool: ...
    def _headers(self, extra: dict[str, Any] | None = None) -> dict[str, str]: ...
    def _request(
        self, method: str, path: str, base: str | None = None, **kwargs: Any
    ) -> Any: ...
    @staticmethod
    def _detail(data: Any) -> str | None: ...
    @staticmethod
    def _parse(response: httpx.Response) -> Any: ...
    def search(
        self, q: str = "", types: list[str] | None = None, license: str = ""
    ) -> list[dict[str, Any]]: ...
    def bundle(self, bundle_id: int | str) -> dict[str, Any]: ...
    def resolve(self, ptype: str, package_id: str) -> dict[str, Any]: ...
    def download(self, ptype: str, package_id: str, version: str) -> bytes: ...
    def waive(self, ptype: str, package_id: str) -> dict[str, Any]: ...
    def login_check(self) -> dict[str, Any]: ...
    def token_info(self) -> dict[str, Any]: ...
    def maintainers(self) -> dict[str, Any]: ...
    def publish(
        self, ptype: str, data: bytes, checksum: str,
        orga: int | None = None, price: float | None = None
    ) -> dict[str, Any]: ...
    def license_search(self, q: str = "") -> list[dict[str, Any]]: ...
    def license_placeholders(
        self, ptype: str, package_id: str, license_id: str
    ) -> dict[str, Any]: ...
    def select_license(
        self, ptype: str, package_id: str, license_id: str, values: dict[str, Any]
    ) -> dict[str, Any]: ...
