from typing import Any

from webfluid import Fluid
from webfluid.extensions.base import FluidExtension
from webfluid.extensions.security.services import UserService, TokenService, HashService, OAuthService


class Security(FluidExtension):
    def __init__(self, fluid: Fluid | None = None) -> None: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **__: Any) -> None: ...
    @property
    def user_service(self) -> UserService: ...
    @property
    def token_service(self) -> TokenService: ...
    @property
    def hash_service(self) -> HashService: ...
    @property
    def oauth_service(self) -> OAuthService: ...
