_codes: dict[str, str]
_policy: PasswordPolicy | None

def validate_username(username: str) -> str: ...

class PasswordPolicy:
    min_length: int
    requirements: dict[str, int]
    def __init__(self, min_length: int, requirements: dict[str, int]) -> None: ...
    def _counts(self, password: str) -> dict[str, int]: ...
    def validate(self, password: str) -> str: ...

default_policy: PasswordPolicy

def set_policy(policy: PasswordPolicy) -> None: ...
def validate_password(password: str) -> str: ...
