from typing import Any

import questionary

style: questionary.Style
qmark: str
pointer: str

def choice(title: str, value: Any) -> questionary.Choice: ...
def fixed_choice(title: str, value: Any) -> questionary.Choice: ...
def select(
    message: str, choices: list[Any], **kwargs: Any
) -> questionary.Question: ...
def checkbox(
    message: str, choices: list[Any], **kwargs: Any
) -> questionary.Question: ...
def text(message: str, **kwargs: Any) -> questionary.Question: ...
def confirm(message: str, **kwargs: Any) -> questionary.Question: ...
def password(message: str, **kwargs: Any) -> questionary.Question: ...

frontend_type: questionary.Question
frontend_framework: questionary.Question
use_typescript: questionary.Question
register_index: questionary.Question
use_alpine: questionary.Question

def confirm_safe_id(given: str, suggestion: str) -> bool: ...
def select_base() -> str: ...
def additive_name(additive_id: str) -> str: ...

version_format: questionary.Question
as_base: questionary.Question
extend: questionary.Question
description: questionary.Question
author: questionary.Question
email: questionary.Question
requirements: questionary.Question

def database_uri(name: str) -> str: ...
def additives(installed: list[tuple[str, str]]) -> list[str]: ...

redis_uri: questionary.Question
mail_username: questionary.Question
mail_password: questionary.Question
extensions: questionary.Question
features: questionary.Question

host: questionary.Question
port: questionary.Question
debug_mode: questionary.Question
menu: questionary.Question

ocean_token: questionary.Question
ocean_license_query: questionary.Question

def ocean_confirm_overwrite(username: str, days: Any) -> questionary.Question: ...
def ocean_confirm_overwrite_invalid() -> questionary.Question: ...
def ocean_confirm_waiver(package_id: str) -> questionary.Question: ...
def _valid_price(value: str, required: bool) -> Any: ...
def ocean_price(required: bool) -> questionary.Question: ...
def ocean_maintainer(options: list[tuple[str, Any]]) -> questionary.Question: ...
def ocean_license_choice(matches: list[dict[str, Any]]) -> questionary.Question: ...
