import subprocess
from pathlib import Path
from typing import Any

import typer

_proc: subprocess.Popen[str] | None
_streaming: bool
_terminate: bool
_log: Any

def _env_from_config(config_file: Path, debug: bool) -> dict[str, str]: ...
def _read_key() -> str: ...
def _exit(signum: int, _: object) -> None: ...
def _stream_log() -> None: ...
def _join_log() -> None: ...
def _start(env: dict[str, str], project_root: Path) -> None: ...
def _stop() -> None: ...
def _restart(env: dict[str, str], project_root: Path) -> None: ...
def _status() -> str: ...
def _clear_logs(log_dir: Path) -> None: ...
def run(
    name: str,
    host: str = ...,
    port: int = ...,
    loglevel: str = ...,
    interactive: bool = ...,
    debug: bool = ...,
) -> None: ...
def cli_entry(app: typer.Typer) -> None: ...
