import re
from pathlib import Path
from typing import Any

_JUNK_DIRS: set[str]
_JUNK_FILES: set[str]
_JUNK_SUFFIXES: tuple[str, ...]
_IGNORE_NAME: str

def _is_junk(rel: str) -> bool: ...
def _glob_to_regex(pattern: str, anchored: bool) -> re.Pattern[str]: ...
def _parse_rule(raw: str) -> tuple[bool, bool, re.Pattern[str]] | None: ...
def _collect_ignores(root: Path, rels: list[str]) -> list[tuple[str, list[Any]]]: ...
def _is_ignored(rel: str, ignores: list[tuple[str, list[Any]]]) -> bool: ...
def _pack(entries: list[tuple[str, bytes]]) -> bytes: ...
def selected_files(root: Path) -> list[str]: ...
def build_archive(root: Path) -> bytes: ...
def sha256_hex(data: bytes) -> str: ...
