from pathlib import Path
from typing import Any

from webfluid.utils.ocean import Ocean

_channels: dict[str, str]

def _parse_spec(spec: str) -> tuple[str, str | None]: ...
def _channel(alpha: bool, beta: bool, rc: bool) -> str: ...
def _latest_in_channel(versions: list[str], channel: str) -> str | None: ...
def _select_version(
    pid: str, meta: dict[str, Any], pinned: str | None, channel: str
) -> str | None: ...
def _installed_additive_ids(additive_root: Path) -> set[str]: ...
def _env_has_package(name: str) -> bool: ...
def _pip_install_editable(target: Path) -> bool: ...
def _install_package(
    ocean: Ocean, ptype: str, pid: str, pinned: str | None,
    channel: str, target: Path
) -> bool: ...
def _install_additives(project_root: Path, dirnames: list[str]) -> None: ...
def install(
    additive: list[str] = ...,
    extension: list[str] = ...,
    alpha: bool = ...,
    beta: bool = ...,
    rc: bool = ...,
) -> None: ...
