from pathlib import Path
from typing import Any

from webfluid.utils.core import Version
from webfluid.utils.ocean import Ocean

_channels: dict[str, str]
_labels: dict[str, str]
_bundle_types: dict[str, str]

def _parse_spec(spec: str) -> tuple[str, str | None]: ...
def _channel(
    alpha: bool, beta: bool, rc: bool, pre: bool, prefer_stable: bool
) -> str: ...
def _wanted(channel: str, prefer_stable: bool) -> str: ...
def _matches(version: Version, channel: str) -> bool: ...
def _latest_in_channel(versions: list[str], channel: str) -> str | None: ...
def _select_version(
    pid: str, meta: dict[str, Any], pinned: str | None,
    channel: str, prefer_stable: bool = False
) -> str | None: ...
def _bundle_ref(value: str) -> str | None: ...
def _pull_bundle(ocean: Ocean, ref: str) -> dict[str, Any] | None: ...
def _add_spec(
    specs: dict[str, list[str]], seen: set[tuple[str, str]],
    ptype: str, spec: str, origin: str | None = None
) -> None: ...
def _collect(
    ocean: Ocean, additives: list[str],
    extensions: list[str], bundles: list[str]
) -> dict[str, list[str]]: ...
def _installed_additive_ids(additive_root: Path) -> set[str]: ...
def _env_has_package(name: str) -> bool: ...
def _pip_install_editable(target: Path) -> bool: ...
def _install_package(
    ocean: Ocean, ptype: str, pid: str, pinned: str | None,
    channel: str, prefer_stable: bool, target: Path
) -> bool: ...
def _install_additives(project_root: Path, dirnames: list[str]) -> None: ...
def install(
    additive: list[str] = ...,
    extension: list[str] = ...,
    bundle: list[str] = ...,
    alpha: bool = ...,
    beta: bool = ...,
    rc: bool = ...,
    pre: bool = ...,
    prefer_stable: bool = ...,
) -> None: ...
