from typing import Any

def truncate(text: str, width: int) -> str: ...
def render_table(
    headers: list[str], rows: list[list[str]], max_widths: list[int] | None = None
) -> str: ...
def package_state(item: dict[str, Any]) -> str: ...
