from pathlib import Path
from typing import Any

from webfluid.utils.ocean import Ocean

def _detect_package(root: Path) -> tuple[str | None, str | None]: ...
def _choose_maintainer(status: dict[str, Any]) -> int | None: ...
def _choose_price(ptype: str) -> float | None: ...
def _select_license(ocean: Ocean, ptype: str, package_id: str) -> None: ...
def publish() -> None: ...
