from typing import Any

def _types(additives: bool, extensions: bool, bundles: bool) -> list[str]: ...
def _license(oss_only: bool, paid_only: bool) -> str: ...
def _packages_table(items: list[dict[str, Any]]) -> None: ...
def _bundles_table(items: list[dict[str, Any]]) -> None: ...
def search(
    query: str = ...,
    additives: bool = ...,
    extensions: bool = ...,
    bundles: bool = ...,
    oss_only: bool = ...,
    paid_only: bool = ...,
) -> None: ...
