from collections.abc import Callable
from typing import Any

class RequestPhase:
    before: bool
    after: bool
    reverse: bool
    _processors: list[Callable[..., Any]]
    def __init__(self, stage: str, reverse: bool = False) -> None: ...
    def add_processor(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    async def _process_before(self) -> Any | None: ...
    async def _process_after(self, response: Any) -> Any: ...
    async def process(self, response: Any = None) -> Any | None: ...

class Lifecycle:
    before: RequestPhase
    after: RequestPhase
    def __init__(self) -> None: ...
    async def process_before(self) -> Any | None: ...
    async def process_after(self, response: Any) -> Any: ...
