from typing import Any

from fastapi import WebSocket

from webfluid.extensions.events.events import Events
from webfluid.extensions.events.queries import Queries
from webfluid.extensions.events.socket.handler import SocketHandler

class SocketManager:
    _handler: SocketHandler
    _websockets: dict[str, WebSocket]
    _subscriptions: dict[str, dict[str, list[Any]]]
    def __init__(self, events: Events, queries: Queries) -> None: ...
    async def socket(self, ws: WebSocket) -> None: ...
    def join(self, ws: WebSocket) -> str: ...
    def get_ws(self, sid: str) -> WebSocket | None: ...
    def leave(self, sid: str) -> None: ...
    def has_subscriptions(self, event: str, sid: str | None = None) -> bool: ...
    def get_subscriptions(
        self, event: str, sid: str | None = None
    ) -> dict[str, list[Any]] | list[Any] | None: ...
    def subscribe(self, event: str, sid: str) -> None: ...
    def unsubscribe(self, event: str, sid: str) -> None: ...
    def add_listener(self, event: str, sid: str, msg_id: Any) -> None: ...
    def get_listeners(self, event: str, sid: str) -> list[Any]: ...
