from collections.abc import AsyncGenerator, Callable
from typing import Any

from fastapi import Request

from webfluid.extensions.security.models.user import User
from webfluid.extensions.security.services.token import TokenService
from webfluid.extensions.security.services.user.gating.requirements import (
    DefaultGate, EmailVerifiedGate, TwoFaGate, AdminGate, RolesGate, AnyRoleGate,
    PermissionsGate, AnyPermissionGate,
)
from webfluid.extensions.security.services.user.gating.bearer import (
    RequirementOrGrantGate, RequirementAndGrantGate,
)


class UserService:
    current_user: Any
    _default_gate: DefaultGate
    _email_verified_gate: EmailVerifiedGate
    _2fa_gate: TwoFaGate
    _admin_gate: AdminGate
    _roles_gate: RolesGate
    _any_role_gate: AnyRoleGate
    _permissions_gate: PermissionsGate
    _any_permission_gate: AnyPermissionGate
    _requirement_or_grant_gate: RequirementOrGrantGate
    _requirement_and_grant_gate: RequirementAndGrantGate

    def __init__(self, token_service: TokenService) -> None: ...
    @staticmethod
    async def current_user_fn(request: Request) -> AsyncGenerator[User | None, None]: ...
    @staticmethod
    async def resolve_bearer(
        request: Request, grant: str
    ) -> AsyncGenerator[tuple[User | None, bool], None]: ...
    @staticmethod
    async def bearer_principal(request: Request, grant: str) -> AsyncGenerator[User | None, None]: ...
    @staticmethod
    def verified_email(user: User) -> bool: ...
    @staticmethod
    def has_2fa(user: User) -> bool: ...
    @staticmethod
    async def is_admin(user: User) -> bool: ...
    @staticmethod
    async def has_roles(user: User, roles: list[str]) -> bool: ...
    @staticmethod
    async def has_any_role(user: User, roles: list[str]) -> bool: ...
    @staticmethod
    async def has_permissions(user: User, permissions: list[str]) -> bool: ...
    @staticmethod
    async def has_any_permission(user: User, permissions: list[str]) -> bool: ...
    @staticmethod
    async def check_requirement(user: User | None, r: dict[str, Any]) -> bool: ...
    @property
    def require_user_fn(self) -> Callable[..., AsyncGenerator[User, None]]: ...
    @property
    def require_user(self) -> Any: ...
    @property
    def require_2fa_fn(self) -> Callable[..., AsyncGenerator[User, None]]: ...
    @property
    def require_2fa(self) -> Any: ...
    @property
    def require_admin_fn(self) -> Callable[..., AsyncGenerator[User, None]]: ...
    @property
    def require_admin(self) -> Any: ...
    def require_roles_fn(self, roles: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_roles(self, roles: list[str]) -> Any: ...
    def require_any_role_fn(self, roles: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_any_role(self, roles: list[str]) -> Any: ...
    def require_permissions_fn(self, permissions: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_permissions(self, permissions: list[str]) -> Any: ...
    def require_any_permission_fn(self, permissions: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_any_permission(self, permissions: list[str]) -> Any: ...
    def requirement_or_grant_fn(self, requirement: dict[str, Any], grant: str) -> Callable[..., AsyncGenerator[User, None]]: ...
    def requirement_or_grant(self, requirement: dict[str, Any], grant: str) -> Any: ...
    def requirement_and_grant_fn(self, requirement: dict[str, Any], grant: str) -> Callable[..., AsyncGenerator[User, None]]: ...
    def requirement_and_grant(self, requirement: dict[str, Any], grant: str) -> Any: ...
