from typing import Any

import questionary

style: questionary.Style
qmark: str
pointer: str

def choice(title: str, value: Any) -> questionary.Choice: ...
def fixed_choice(title: str, value: Any) -> questionary.Choice: ...
def select(
    message: str, choices: list[Any], **kwargs: Any
) -> questionary.Question: ...
def checkbox(
    message: str, choices: list[Any], **kwargs: Any
) -> questionary.Question: ...
def text(message: str, **kwargs: Any) -> questionary.Question: ...
def confirm(message: str, **kwargs: Any) -> questionary.Question: ...
def password(message: str, **kwargs: Any) -> questionary.Question: ...
