from typing import Any

import questionary

token: questionary.Question
license_query: questionary.Question

def _valid_price(value: str, required: bool) -> Any: ...
def confirm_overwrite(username: str, days: Any) -> questionary.Question: ...
def confirm_overwrite_invalid() -> questionary.Question: ...
def confirm_waiver(package_id: str) -> questionary.Question: ...
def price(required: bool) -> questionary.Question: ...
def maintainer(options: list[tuple[str, Any]]) -> questionary.Question: ...
def license_choice(matches: list[dict[str, Any]]) -> questionary.Question: ...
