[project]
name = "webfluid-stubs"
version = "1.0.0b3"
requires-python = ">=3.14"
dependencies = ["webfluid==1.0.0b3"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["webfluid-stubs"]

[tool.setuptools.package-data]
"webfluid-stubs" = ["**/*.pyi"]
