from collections.abc import Callable
from typing import Any

def required_arg_count(fn: Callable[..., Any]) -> int: ...
async def async_result(result: Any) -> Any: ...
async def safe_execute(
    fn: Callable[..., Any], reraise: bool, *args: Any, **kwargs: Any
) -> Any: ...
async def run_in_executor(
    fn: Callable[..., Any], *args: Any, executor: Any = None
) -> Any: ...
