from types import ModuleType
from typing import Any

def enabled(key: str) -> bool: ...
def random_code(length: int = 6) -> str: ...
def safe_string(text: str) -> str: ...
def camel_to_snake(text: str) -> str: ...
def get_root_path(import_name: str) -> str: ...
def parse_config(key: str, value: str) -> tuple[str, str]: ...
def check_priority(priority: int) -> None: ...
def build_sorted_tuple(
    data: dict[int, Any], defaults: tuple[Any, ...] | None = None
) -> tuple[Any, ...]: ...
def try_import(name: str) -> ModuleType | None: ...
