from packaging.version import Version as _Version

class Version(_Version):
    def __init__(self, *parts: object) -> None: ...
    @property
    def stage(self) -> str: ...
    @property
    def build(self) -> int: ...

def check_required_version(
    requirement: str, version_type: str = "framework",
    additive_version: Version | str | None = None
) -> bool: ...
