from contextlib import AbstractContextManager, AbstractAsyncContextManager
from typing import Any

from webfluid import Fluid
from webfluid.extensions.base import FluidExtension
from webfluid.extensions.sqlalchemy.utils import Model, Bind, Executor, AsyncExecutor


class SQLAlchemy(FluidExtension):
    Model: type[Model]
    def __init__(self, fluid: Fluid | None = None, base: type[Model] = ...) -> None: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **__: Any) -> None: ...
    def _resolve_bind(self, bind_key: str | None, model: Any) -> Bind: ...
    def get_bind(self, bind_key: str) -> Bind: ...
    def get_bind_for_model(self, model: Any) -> Bind: ...
    def executor(self, bind_key: str | None = None, model: Any = None) -> AbstractContextManager[Executor]: ...
    def async_executor(self, bind_key: str | None = None, model: Any = None) -> AbstractAsyncContextManager[AsyncExecutor]: ...
    def ensured_executor(self, bind_key: str | None = None, model: Any = None) -> AbstractContextManager[Executor]: ...
    def ensured_async_executor(self, bind_key: str | None = None, model: Any = None) -> AbstractAsyncContextManager[AsyncExecutor]: ...
    @property
    def current_executor(self) -> Executor: ...
    @property
    def current_async_executor(self) -> AsyncExecutor: ...
    @property
    def bind_keys(self) -> list[str]: ...
    @classmethod
    def get_instance(cls) -> SQLAlchemy: ...
