from contextlib import AbstractContextManager, AbstractAsyncContextManager
from contextvars import ContextVar
from typing import Any

from sqlalchemy import MetaData, Table
from sqlalchemy.orm import DeclarativeBase, Session
from sqlalchemy.ext.asyncio import AsyncSession

from webfluid.core.context import BaseContext


class Model(DeclarativeBase):
    __bind_set__: bool
    __metadata__: dict[str, MetaData]
    def __init_subclass__(cls, **kwargs: Any) -> None: ...
    def __hash__(self) -> int: ...
    @classmethod
    def metadata_for(cls, key: str) -> MetaData: ...
    @classmethod
    def set_bind(cls, key: str) -> None: ...


class Bind:
    name: str
    metadata: MetaData
    def __init__(self, key: str, uris: tuple[str, str], metadata: MetaData | None = None) -> None: ...
    def session(self) -> AbstractContextManager[Session]: ...
    def async_session(self) -> AbstractAsyncContextManager[AsyncSession]: ...


class Executor(BaseContext):
    _ctx: ContextVar[Any]
    session: Session
    def __init__(self, session: Session) -> None: ...
    def exec(self, statement: Any, scalars: bool = True) -> Any: ...
    def insert(self, obj: Any, flush: bool = False) -> Any: ...
    def delete(self, obj: Any, flush: bool = False) -> None: ...
    def flush(self) -> None: ...


class AsyncExecutor(BaseContext):
    _ctx: ContextVar[Any]
    session: AsyncSession
    def __init__(self, session: AsyncSession) -> None: ...
    async def exec(self, statement: Any, scalars: bool = True) -> Any: ...
    async def insert(self, obj: Any, flush: bool = False) -> Any: ...
    async def delete(self, obj: Any, flush: bool = False) -> None: ...
    async def flush(self) -> None: ...


def database_uris(uri: str) -> tuple[str, str]: ...
def update_metadata(
    table: Table,
    target_md: MetaData | None = None,
    target_bind: str | None = None,
    target_model: type | None = None,
) -> None: ...
