from concurrent.futures import ThreadPoolExecutor

from argon2 import PasswordHasher

class HashService:
    _hasher: PasswordHasher
    _executor: ThreadPoolExecutor
    def __init__(
        self, time_cost: int, memory_cost: int,
        parallelism: int, threads: int = 4
    ) -> None: ...
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...
    async def ahash(self, password: str) -> str: ...
    async def averify(self, password_hash: str, password: str) -> bool: ...
