class HashService:
    def __init__(self, time_cost: int, memory_cost: int, parallelism: int) -> None: ...
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...
