from typing import Any

from fastapi import Request
from fastapi.responses import JSONResponse


class TokenService:
    csrf_protect: Any
    def __init__(self, secret: str, max_age: int, csrf_cookie: str, csrf_secure: bool) -> None: ...
    def generate_token(self, data: dict[str, Any], salt: str = "csrf") -> str: ...
    async def validate_token(self, token: str, salt: str = "csrf") -> dict[str, Any]: ...
    def csrf_response(self, request: Request) -> JSONResponse: ...
    async def csrf_protect_fn(self, request: Request) -> None: ...
