from collections.abc import AsyncGenerator, Callable
from typing import Any

from fastapi import Request
from fastapi.params import Depends as DependsParam

from webfluid.extensions.security.models.user import User
from webfluid.extensions.security.services.token import TokenService


class UserService:
    current_user: Any
    require_user: Any
    require_user_fn: Callable[..., AsyncGenerator[User, None]]
    require_2fa: Any
    require_2fa_fn: Callable[..., AsyncGenerator[User, None]]
    require_admin: Any
    require_admin_fn: Callable[..., AsyncGenerator[User | None, None]]

    def __init__(self, token_service: TokenService) -> None: ...
    @staticmethod
    async def current_user_fn(request: Request) -> AsyncGenerator[User | None, None]: ...
    @staticmethod
    async def resolve_bearer(
        request: Request, grant: str
    ) -> AsyncGenerator[tuple[User | None, bool], None]: ...
    @staticmethod
    async def bearer_principal(request: Request, grant: str) -> AsyncGenerator[User | None, None]: ...
    @staticmethod
    def _require_user(token_service: TokenService) -> Callable[..., AsyncGenerator[User, None]]: ...
    @staticmethod
    def has_2fa(user: User) -> bool: ...
    def _require_2fa(self) -> Callable[..., AsyncGenerator[User, None]]: ...
    @staticmethod
    async def is_admin(user: User) -> bool: ...
    def _require_admin(self) -> Callable[..., AsyncGenerator[User | None, None]]: ...
    @staticmethod
    async def has_roles(user: User, roles: list[str]) -> bool: ...
    def require_roles_fn(self, roles: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_roles(self, roles: list[str]) -> DependsParam: ...
    @staticmethod
    async def has_any_role(user: User, roles: list[str]) -> bool: ...
    def require_any_role_fn(self, roles: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_any_role(self, roles: list[str]) -> DependsParam: ...
    @staticmethod
    async def has_permissions(user: User, permissions: list[str]) -> bool: ...
    def require_permissions_fn(self, permissions: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_permissions(self, permissions: list[str]) -> DependsParam: ...
    @staticmethod
    async def has_any_permission(user: User, permissions: list[str]) -> bool: ...
    def require_any_permission_fn(self, permissions: list[str]) -> Callable[..., AsyncGenerator[User, None]]: ...
    def require_any_permission(self, permissions: list[str]) -> DependsParam: ...
    def requirement_or_grant_fn(self, requirement: dict[str, Any], grant: str) -> Callable[..., AsyncGenerator[User, None]]: ...
    def requirement_or_grant(self, requirement: dict[str, Any], grant: str) -> DependsParam: ...
    def requirement_and_grant_fn(self, requirement: dict[str, Any], grant: str) -> Callable[..., AsyncGenerator[User, None]]: ...
    def requirement_and_grant(self, requirement: dict[str, Any], grant: str) -> DependsParam: ...
    @classmethod
    async def check_requirement(cls, user: User, r: dict[str, Any]) -> bool: ...
