from collections.abc import AsyncIterator, Callable, Iterator
from contextlib import asynccontextmanager, contextmanager
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import typer
from babel import Locale
from fastapi import WebSocket

from webfluid import Fluid
from webfluid.core.context import BaseContext
from webfluid.extensions.base import FluidExtension
from webfluid.extensions.babel.domain import Domain
from webfluid.extensions.babel.speaklater import LazyString

class _DomainContext(BaseContext):
    domain: Domain
    def __init__(self, domain: Domain) -> None: ...

class SelectorContext(BaseContext):
    locale_selector: Callable[..., Any] | None
    timezone_selector: Callable[..., Any] | None
    def __init__(
        self,
        locale_selector: Callable[..., Any] | None,
        timezone_selector: Callable[..., Any] | None,
    ) -> None: ...

class Babel(FluidExtension):
    _cli: typer.Typer
    _api_whitelist: set[str]
    default_domain: Domain | None
    default_locale: str | None
    default_timezone: str | None
    supported_locales: tuple[str, ...] | None
    date_formats: Any
    def __init__(
        self, fluid: Fluid | None = None, default_domain: Domain | None = None
    ) -> None: ...
    def expand_fluid(
        self, fluid: Fluid, *_: Any, default_domain: Domain | None = None
    ) -> None: ...
    def register_domain(self, name: str, package: Path | None = None) -> None: ...
    async def load_translations(self) -> None: ...
    def update_translations(
        self,
        domain: str,
        translations: Callable[
            [], dict[str, dict[str, dict[tuple[str, str | None], str]]]
        ],
    ) -> None: ...
    async def _update_translations(self) -> None: ...
    async def socket_i18n(self, ws: WebSocket) -> None: ...
    def locale_selector(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def timezone_selector(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def domain_context(self, domain: str) -> Callable[..., Any]: ...
    def gettext(self, string: str, **variables: Any) -> str: ...
    def ngettext(self, singular: str, plural: str, num: int, **variables: Any) -> str: ...
    def pgettext(self, context: str, string: str, **variables: Any) -> str: ...
    def npgettext(
        self, context: str, singular: str, plural: str, num: int, **variables: Any
    ) -> str: ...
    def lazy_gettext(self, string: str, **variables: Any) -> LazyString: ...
    def lazy_ngettext(
        self, singular: str, plural: str, num: int, **variables: Any
    ) -> LazyString: ...
    def lazy_pgettext(self, context: str, string: str, **variables: Any) -> LazyString: ...
    def lazy_npgettext(
        self, context: str, singular: str, plural: str, num: int, **variables: Any
    ) -> LazyString: ...
    @property
    def _fallback_escalation(self) -> list[Domain]: ...
    @property
    def current_domain(self) -> Domain: ...
    @property
    def locale_selector_fn(self) -> Callable[..., Any] | None: ...
    @property
    def timezone_selector_fn(self) -> Callable[..., Any] | None: ...
    @staticmethod
    @contextmanager
    def force(
        locale: str | Locale | None = None, timezone: str | ZoneInfo | None = None
    ) -> Iterator[None]: ...
    @staticmethod
    @asynccontextmanager
    def aforce(
        locale: str | Locale | None = None, timezone: str | ZoneInfo | None = None
    ) -> AsyncIterator[None]: ...
    @staticmethod
    def extract_fallback(project_root: Path) -> None: ...
    @staticmethod
    def extract() -> None: ...
