from collections.abc import Callable, Iterator
from typing import Any

class LazyString:
    _func: Callable[..., str]
    _args: tuple[Any, ...]
    _kwargs: dict[str, Any]
    def __init__(self, func: Callable[..., str], *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, attr: str) -> Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, item: Any) -> bool: ...
    def __add__(self, other: Any) -> str: ...
    def __radd__(self, other: Any) -> str: ...
    def __mul__(self, other: Any) -> str: ...
    def __rmul__(self, other: Any) -> str: ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    def __html__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __mod__(self, other: Any) -> str: ...
    def __rmod__(self, other: Any) -> str: ...
