from collections.abc import Callable
from datetime import date, datetime, time, timedelta
from decimal import Decimal
from pathlib import Path
from typing import Any, Literal
from zoneinfo import ZoneInfo

from babel import Locale

from webfluid.extensions.babel.constants import DateFormat, DateFormatKey

def translation_resolver(
    path: Path, locale_map: dict[str, int]
) -> Callable[[], dict[str, Any]]: ...
def parse_best_match(
    accept_header: str | None, available: tuple[str, ...]
) -> str | None: ...
def load_locale(locale: str) -> Locale: ...
def get_locale() -> Locale: ...
def get_timezone() -> ZoneInfo: ...
def format_message(message: str, **variables: Any) -> str: ...
def _get_format(key: DateFormatKey, fmt: DateFormat = None) -> Any: ...
def to_user_timezone(dt: datetime) -> datetime: ...
def to_utc(dt: datetime) -> datetime: ...
def format_datetime(
    dt: datetime | None = None, fmt: DateFormat = None, rebase: bool = True
) -> str: ...
def format_date(
    d: datetime | date | None = None, ftm: DateFormat = None, rebase: bool = True
) -> str: ...
def format_time(
    t: datetime | None = None, fmt: DateFormat = None, rebase: bool = True
) -> str: ...
def format_timedelta(
    datetime_or_timedelta: datetime | timedelta,
    granularity: Literal[
        "year", "month", "week", "day", "hour", "minute", "second"
    ] = "second",
    add_direction: bool = False,
    threshold: float = 0.85,
) -> str: ...
def _date_format(
    formatter: Callable[..., str],
    obj: datetime | date | time | None,
    fmt: Any,
    rebase: bool | None,
    **extra: Any,
) -> str: ...
def format_number(number: float | Decimal | str) -> str: ...
def format_decimal(number: float | Decimal | str, fmt: str | None = None) -> str: ...
def format_currency(
    number: float | Decimal | str,
    currency: str,
    fmt: str | None = None,
    currency_digits: bool = True,
    format_type: Literal["name", "standard", "accounting"] = "standard",
) -> str: ...
def format_percent(number: float | Decimal | str, fmt: str | None = None) -> str: ...
def format_scientific(number: float | Decimal | str, fmt: str | None = None) -> str: ...
def fake_t(s: str, **args: Any) -> str: ...
def fake_tn(s: str, p: str, n: int, **args: Any) -> str: ...
