from collections.abc import Callable
from contextlib import AbstractContextManager, AbstractAsyncContextManager
from typing import Any

import typer

from webfluid import Fluid
from webfluid.extensions.base import FluidExtension
from webfluid.extensions.babel.domain import Domain
from webfluid.extensions.babel.speaklater import LazyString
from webfluid.extensions.babel.babel.socket import Socket
from webfluid.extensions.babel.babel.translation import Translator


class Babel(FluidExtension):
    _cli: typer.Typer
    _translator: Translator | None
    _socket: Socket | None
    default_locale: str | None
    default_timezone: str | None
    supported_locales: tuple[str, ...] | None
    date_formats: Any
    def __init__(
        self, fluid: Fluid | None = None, default_domain: Domain | None = None
    ) -> None: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **kwargs: Any) -> None: ...
    def _ensure_initialized(self) -> None: ...
    @property
    def gettext(self) -> Callable[..., str]: ...
    @property
    def ngettext(self) -> Callable[..., str]: ...
    @property
    def pgettext(self) -> Callable[..., str]: ...
    @property
    def npgettext(self) -> Callable[..., str]: ...
    @property
    def lazy_gettext(self) -> Callable[..., LazyString]: ...
    @property
    def lazy_ngettext(self) -> Callable[..., LazyString]: ...
    @property
    def lazy_pgettext(self) -> Callable[..., LazyString]: ...
    @property
    def lazy_npgettext(self) -> Callable[..., LazyString]: ...
    @property
    def register_domain(self) -> Callable[..., None]: ...
    @property
    def domain_context(self) -> Callable[..., Callable[..., Any]]: ...
    @property
    def current_domain(self) -> Domain: ...
    @property
    def update_translations(self) -> Callable[..., None]: ...
    @property
    def locale_selector(self) -> Callable[..., Callable[..., Any]]: ...
    @property
    def timezone_selector(self) -> Callable[..., Callable[..., Any]]: ...
    @property
    def locale_selector_fn(self) -> Callable[..., Any] | None: ...
    @property
    def timezone_selector_fn(self) -> Callable[..., Any] | None: ...
    @property
    def force(self) -> Callable[..., AbstractContextManager[None]]: ...
    @property
    def aforce(self) -> Callable[..., AbstractAsyncContextManager[None]]: ...
