class FluidVersion(tuple[int, int, int]):
    stage: str
    build: int
    def __init__(self, major: str, minor: str, patch: str) -> None: ...
    def __new__(cls, major: str, minor: str, patch: str) -> FluidVersion: ...
    def __str__(self) -> str: ...

def version() -> FluidVersion: ...
