class FrameworkException(Exception): ...

class FrontendException(FrameworkException): ...
class NodeError(FrontendException): ...
class TailwindError(FrontendException): ...

class AdditiveException(FrameworkException): ...
class ManifestError(AdditiveException): ...

class OceanError(FrameworkException):
    status: int
    detail: str
    def __init__(self, status: int, detail: str) -> None: ...
