from typing import Any

from webfluid import Fluid
from webfluid.core.lifecycle.phase import Phase

class Lifecycle:
    before_enable: Phase
    after_enable: Phase
    def __init__(self) -> None: ...
    async def _run(self, phase: Phase, *args: Any) -> None: ...
    async def run_before(self, fluid: Fluid) -> None: ...
    async def run_after(self) -> None: ...
