from webfluid.core.lifecycle.phase import Phase

class Lifecycle:
    startup: Phase
    shutdown: Phase
    def __init__(self) -> None: ...
    async def _run(self, phase: Phase) -> None: ...
    async def run_startup(self) -> None: ...
    async def run_shutdown(self) -> None: ...
