from collections.abc import Callable
from typing import Any

class HookPhase:
    name: str
    reverse: bool
    _hooks: list[Callable[..., Any]]
    _locked: bool
    def __init__(self, name: str, reverse: bool = False) -> None: ...
    def add_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    async def run_hooks(self) -> None: ...

class Lifecycle:
    startup: HookPhase
    shutdown: HookPhase
    def __init__(self) -> None: ...
    async def run_startup(self) -> None: ...
    async def run_shutdown(self) -> None: ...
