from pathlib import Path
from configparser import ConfigParser
from typing import Any

import typer

create: typer.Typer

def _make_defaults(
    base: Path, api_init: str, api_v1: str, app_init: str, index_py: str
) -> None: ...
def _frontend_conf() -> dict[str, Any]: ...
def _inject_base(code: str, prefix: str = "") -> str: ...
def _create_frontend(
    base: Path, conf: dict[str, Any], space: str, name: str
) -> bool: ...
def _setup_additives(config: ConfigParser) -> None: ...
def project(
    name: str,
    skip_defaults: bool = ...,
    skip_frontend: bool = ...,
    babel_fallback: bool = ...,
) -> None: ...
def additive(additive_id: str) -> None: ...
def create_app(name: str, secret_length: int = ...) -> None: ...
def cli_entry(app: typer.Typer) -> None: ...
