from configparser import ConfigParser
from pathlib import Path
from typing import Any

def make_defaults(
    base: Path, api_init: str, api_v1: str, app_init: str, index_py: str
) -> None: ...
def frontend_conf() -> dict[str, Any]: ...
def inject_base(code: str, prefix: str = "") -> str: ...
def create_frontend(
    base: Path, conf: dict[str, Any], space: str, name: str
) -> bool: ...
def setup_additives(config: ConfigParser) -> None: ...
