import asyncio
from collections import deque
from collections.abc import AsyncGenerator, Callable
from typing import Any

from fastapi import WebSocket

from webfluid import Fluid
from webfluid.extensions.base import FluidExtension

class _Listener:
    buffer: deque[Any]
    event: asyncio.Event
    def __init__(self, maxlen: int | None) -> None: ...

class _BroadCaster:
    listeners: set[_Listener]
    queue_size: int
    def __init__(self, queue_size: int) -> None: ...
    def stream(self) -> AsyncGenerator[Any]: ...
    def publish(self, data: Any) -> None: ...

class EventManager(FluidExtension):
    def __init__(self, fluid: Fluid | None = None) -> None: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **__: Any) -> None: ...
    async def _socket_manager(self, ws: WebSocket) -> None: ...
    async def _event_loop(self, event: str) -> None: ...
    def _prepare_event(self, name: str, singleton: bool, internal: bool) -> None: ...
    def create_signal(
        self, name: str, singleton: bool = False, internal: bool = False
    ) -> None: ...
    def event(
        self, name: str, singleton: bool = False, internal: bool = True
    ) -> Callable[..., Any]: ...
    def query(
        self, name: str, singleton: bool = True, internal: bool = True
    ) -> Callable[..., Any]: ...
    def trigger(self, event: str, data: Any | None = None) -> None: ...
    async def listen(self, event: str) -> AsyncGenerator[Any | None]: ...
    async def request(self, query: str, data: Any | None = None) -> Any | list[Any]: ...
