from typing import Any

from webfluid.core.fluid import Fluid
from webfluid.extensions.base import FluidExtension

class JWTManager(FluidExtension):
    def __init__(self, fluid: Fluid | None = None) -> None: ...
    async def _rotate_secret(self) -> None: ...
    def _encode(
        self, payload: dict[str, Any], audience: str, secret: str,
        expire: int | None, kid: str
    ) -> str: ...
    def _decode(self, token: str, audience: str, secret: str) -> dict[str, Any]: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **__: Any) -> None: ...
    def encode(
        self, payload: dict[str, Any], audience: str = "default",
        expire: int | None = None
    ) -> str: ...
    async def aencode(
        self, payload: dict[str, Any], audience: str = "default",
        expire: int | None = None
    ) -> str: ...
    def decode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
    async def adecode(self, token: str, audience: str = "default") -> dict[str, Any]: ...
    @staticmethod
    def _current_key(cache: Any) -> str: ...
    @staticmethod
    async def _acurrent_key(cache: Any) -> str: ...
