import asyncio
from collections.abc import AsyncGenerator, Callable
from typing import Any

from webfluid.extensions.events.broadcast import BroadCaster

class Events:
    _event_queue_size: int
    _ctx_decorator: Callable[[Callable[..., Any]], Callable[..., Any]]
    _broadcasters: dict[str, BroadCaster]
    _events: dict[str, dict[str, Any]]
    _pending: list[str] | None
    create_loop: Callable[[str], asyncio.Task[Any]] | None
    def __init__(
        self, queue_size: int,
        ctx_decorator: Callable[[Callable[..., Any]], Callable[..., Any]]
    ) -> None: ...
    def _create_loop(self, name: str) -> None: ...
    def _prepare_event(self, name: str, singleton: bool, internal: bool) -> None: ...
    def create_pending_loops(self) -> None: ...
    def create_signal(
        self, name: str, singleton: bool = False, internal: bool = False
    ) -> None: ...
    def event(
        self, name: str, singleton: bool = False, internal: bool = True
    ) -> Callable[..., Any]: ...
    def trigger(self, event: str, data: Any | None = None) -> None: ...
    async def listen(self, event: str) -> AsyncGenerator[Any | None]: ...
    def has_event(self, event: str) -> bool: ...
    def is_singleton(self, event: str) -> bool: ...
    def is_internal(self, event: str) -> bool: ...
    def broadcaster(self, event: str) -> BroadCaster | None: ...
    def handlers(self, event: str) -> list[Callable[..., Any]]: ...
