from typing import Any
from collections.abc import AsyncGenerator, Awaitable, Callable

from webfluid import Fluid
from webfluid.extensions.base import FluidExtension
from webfluid.extensions.events.events import Events
from webfluid.extensions.events.queries import Queries

class EventManager(FluidExtension):
    _events: Events | None
    _queries: Queries | None
    def __init__(self, fluid: Fluid | None = None) -> None: ...
    def expand_fluid(self, fluid: Fluid, *_: Any, **__: Any) -> None: ...
    def _ensure_initialized(self) -> None: ...
    @property
    def create_signal(self) -> Callable[..., None]: ...
    @property
    def event(self) -> Callable[..., Callable[..., Any]]: ...
    @property
    def trigger(self) -> Callable[..., None]: ...
    @property
    def listen(self) -> Callable[..., AsyncGenerator[Any | None]]: ...
    @property
    def query(self) -> Callable[..., Callable[..., Any]]: ...
    @property
    def request(self) -> Callable[..., Awaitable[Any | list[Any]]]: ...
