from collections.abc import Callable
from typing import Any

class Queries:
    _ctx_decorator: Callable[[Callable[..., Any]], Callable[..., Any]]
    _queries: dict[str, dict[str, Any]]
    def __init__(
        self, ctx_decorator: Callable[[Callable[..., Any]], Callable[..., Any]]
    ) -> None: ...
    def query(
        self, name: str, singleton: bool = True, internal: bool = True
    ) -> Callable[..., Any]: ...
    async def request(self, query: str, data: Any | None = None) -> Any | list[Any]: ...
    def has_query(self, query: str) -> bool: ...
    def is_singleton(self, query: str) -> bool: ...
    def is_internal(self, query: str) -> bool: ...
    def handlers(self, query: str) -> list[Callable[..., Any]]: ...
