FRAMEWORK_ID: str

APP_STATIC: str
FRAMEWORK_STATIC: str
HUB_API: str
HUB_AUTH: str

FEATURE_FLAGS: tuple[str, ...]
EXTENSION_FLAGS: tuple[str, ...]

DEBUG: bool
EXECUTION: bool
THEMES: bool
TAILWIND: bool
CHECK_FRONTEND: bool
BUILD_FRONTEND: bool
PROCESSING: bool
ADDITIVES: bool

EXT_SCHEDULING: bool
EXT_SQLALCHEMY: bool
EXT_BABEL: bool
EXT_SECURITY: bool
EXT_EVENTS: bool
EXT_CACHE: bool
EXT_MAIL: bool
EXT_JWT: bool

DEV_AUTO_INSTALL: bool
