from contextvars import ContextVar
from contextlib import contextmanager
from collections.abc import Iterator
from typing import Any

from fastapi import Request
from webfluid import Fluid

class BaseContext:
    _ctx: ContextVar[Any]
    _tokens: list[Any]
    def __enter__(self) -> BaseContext: ...
    def __exit__(self, *args: object) -> bool: ...
    async def __aenter__(self) -> BaseContext: ...
    async def __aexit__(self, *args: object) -> bool: ...
    @classmethod
    def current(cls) -> BaseContext: ...
    @classmethod
    @contextmanager
    def outer(cls, depth: int = 1) -> Iterator[BaseContext | None]: ...

class FluidContext(BaseContext):
    _ctx: ContextVar[FluidContext]
    _ctx_cache: dict[str, Any]
    fluid: Fluid
    request: Request | None
    def __init__(
        self, fluid: Fluid, request: Request | None = None,
        *args: Any, **kwargs: Any
    ) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def pop(self, key: str, default: Any = None) -> Any: ...
    @classmethod
    def get_ctx_data(
        cls, default_config: object, *requirements: str
    ) -> Any | tuple[Any, ...]: ...
