from collections.abc import Callable
from typing import Any
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from jinja2 import Environment, ChoiceLoader
from markupsafe import Markup
from uvicorn.middleware.proxy_headers import ProxyHeadersMiddleware

from webfluid.core.config import Config
from webfluid.surface.frontend import Frontend

class Fluid(FastAPI):
    name: str
    app_root: Path
    additive_root: Path
    config: Config
    app_static: StaticFiles | None
    framework_static: StaticFiles
    static_prefixes: set[str]
    jinja_env: Environment
    sources: tuple[Markup, ...] | None
    app_loader: ChoiceLoader
    framework_loader: ChoiceLoader
    frontend: Frontend
    def __init__(self, import_name: str) -> None: ...
    def __repr__(self) -> str: ...
    async def _prepare(self) -> None: ...
    async def _startup(self) -> None: ...
    async def _shutdown(self) -> None: ...
    async def _run_server(self) -> None: ...
    def _handle_shutdown(self, *_: Any) -> None: ...
    def _validate_theme(self, name: str) -> None: ...
    def startup_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def shutdown_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def add_source(self, src: str, priority: int = 1) -> None: ...
    def add_theme(self, name: str, link: Markup) -> None: ...
    def get_theme(self) -> Markup: ...
    def set_theme(self, request: Request, name: str) -> None: ...
    def context_processor(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def before_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def after_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    async def render(self, template: str, **ctx: Any) -> str: ...
    async def start(self) -> None: ...
    def mix(self) -> None: ...
    @property
    def asgi_app(self) -> Fluid | ProxyHeadersMiddleware: ...
    @property
    def limit(self) -> Callable[..., Any]: ...
