from typing import Any

class Freezable:
    label: str
    closed_after: str
    _frozen: Any | None
    def __init__(self) -> None: ...
    @property
    def is_frozen(self) -> bool: ...
    @property
    def frozen(self) -> Any: ...
    def guard(self) -> None: ...
    def freeze(self, value: Any) -> Any: ...
