from pathlib import Path

FRAMEWORK_ROOT: Path
FRAMEWORK_PACKAGE: str

FRAMEWORK_ID: str
FRAMEWORK_NAME: str
FRAMEWORK_ABBR: str
FRAMEWORK_SITE: str
FRAMEWORK_DOCS: str

HUB_NAME: str
HUB_API_URL: str
HUB_AUTH_URL: str

CLI_NAME: str
ENV_PREFIX: str

MAIN_LOGGER: str
ADDITIVE_LOGGER: str
EXTENSION_GROUP: str

REQUIRES_KEY: str
IDENTITY_ROUTE: str
HUB_TOKEN_FILE: str

BASE_TEMPLATE: str
STATIC_MOUNT: str
STATIC_GLOBAL: str
TAILWIND_GLOBAL: str
