from contextvars import ContextVar
from contextlib import contextmanager
from collections.abc import Iterator
from typing import Any

class BaseContext:
    _ctx: ContextVar[Any]
    _tokens: list[Any]
    def __enter__(self) -> BaseContext: ...
    def __exit__(self, *args: object) -> bool: ...
    async def __aenter__(self) -> BaseContext: ...
    async def __aexit__(self, *args: object) -> bool: ...
    @classmethod
    def current(cls) -> BaseContext: ...
    @classmethod
    @contextmanager
    def outer(cls, depth: int = 1) -> Iterator[BaseContext | None]: ...
