from collections.abc import Callable, ItemsView, KeysView, ValuesView
from contextvars import ContextVar
from typing import Any

from fastapi import Request

from webfluid import Fluid
from webfluid.core.context.base import BaseContext

class FluidContext(BaseContext):
    _ctx: ContextVar[FluidContext]
    fluid: Fluid
    request: Request | None
    _data: dict[str, Any]
    _cache: dict[str, Any]
    def __init__(
        self, fluid: Fluid, request: Request | None = None,
        *args: Callable[..., Any], **kwargs: Any
    ) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, item: str) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def keys(self) -> KeysView[str]: ...
    def values(self) -> ValuesView[Any]: ...
    def items(self) -> ItemsView[str, Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def pop(self, key: str, default: Any = None) -> Any: ...
    def cached[T](self, key: str, factory: Callable[[], T]) -> T: ...
    @classmethod
    def cached_or[T](cls, key: str, factory: Callable[[], T]) -> T: ...
