from collections.abc import Callable
from typing import Any
from pathlib import Path

from fastapi import FastAPI, Request
from jinja2 import Environment, BaseLoader
from markupsafe import Markup

from webfluid.core.config import Config
from webfluid.surface.frontend import Frontend
from webfluid.core.fluid.static import StaticFiles, StaticPrefixes
from webfluid.core.lifecycle import FluidLifecycle, RequestLifecycle
from webfluid.core.fluid.jinja import Jinja
from webfluid.core.fluid.sources import Sources, Themes
from webfluid.core.fluid.ratelimit import Limiter
from webfluid.core.fluid.server import Server

class Fluid(FastAPI):
    config: Config
    name: str
    app_root: Path
    additive_root: Path
    static_files: StaticFiles
    static_prefixes: StaticPrefixes
    frontend: Frontend
    _lifecycle: FluidLifecycle
    _request_lifecycle: RequestLifecycle
    _jinja: Jinja
    _sources: Sources
    _themes: Themes
    _limiter: Limiter
    _server: Server
    def __init__(self, import_name: str) -> None: ...
    def __repr__(self) -> str: ...
    async def _prepare(self) -> None: ...
    def startup_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def shutdown_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def before_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def after_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def context_processor(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def add_template_loader(self, loader: BaseLoader) -> None: ...
    def add_source(self, src: str, priority: int = 1) -> None: ...
    def add_theme(self, name: str, link: Markup) -> None: ...
    def get_theme(self) -> Markup: ...
    def set_theme(self, request: Request, name: str) -> None: ...
    async def render(self, template: str, **ctx: Any) -> str: ...
    def mix(self) -> None: ...
    @property
    def jinja_env(self) -> Environment: ...
    @property
    def sources(self) -> tuple[Markup, ...] | None: ...
    @property
    def limit(self) -> Callable[..., Any]: ...
