from collections.abc import Callable
from typing import Any
from pathlib import Path

from fastapi import FastAPI, Request
from jinja2 import Environment, BaseLoader
from markupsafe import Markup
from starlette.datastructures import URLPath

from webfluid.core.config import Config
from webfluid.surface.frontend import Frontend
from webfluid.core.fluid.routing import Routes
from webfluid.core.fluid.static import StaticFiles, StaticPrefixes
from webfluid.core.lifecycle import FluidLifecycle, RequestLifecycle
from webfluid.core.fluid.jinja import Jinja
from webfluid.core.fluid.sources import Sources, Themes
from webfluid.core.fluid.ratelimit import Limiter
from webfluid.core.fluid.server import Server

_moved: dict[str, str]

class Fluid(FastAPI):
    config: Config
    name: str
    project_root: Path
    additive_root: Path
    static_files: StaticFiles
    static_prefixes: StaticPrefixes
    frontend: Frontend
    _lifecycle: FluidLifecycle
    _request_lifecycle: RequestLifecycle
    _routes: Routes
    _jinja: Jinja
    _sources: Sources
    _themes: Themes
    _limiter: Limiter
    _server: Server
    def __init__(self, import_name: str) -> None: ...
    def __repr__(self) -> str: ...
    def _build_lifecycle(self) -> None: ...
    def _build_rendering(self) -> None: ...
    def _build_static(self) -> None: ...
    def _build_serving(self) -> None: ...
    def _build_features(self) -> None: ...
    def _build_middleware(self) -> None: ...
    async def _prepare(self) -> None: ...
    def url_path_for(self, name: str, /, **path_params: Any) -> URLPath: ...
    def startup_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def shutdown_hook(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def before_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def after_request(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def context_processor(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...
    def add_template_loader(self, loader: BaseLoader) -> None: ...
    def add_source(self, src: str, priority: int = 1) -> None: ...
    def add_theme(self, name: str, link: Markup | str) -> None: ...
    def get_theme(self) -> Markup: ...
    def set_theme(self, request: Request, name: str) -> None: ...
    async def render(self, template: str, **ctx: Any) -> str: ...
    async def render_string(self, source: str, **ctx: Any) -> str: ...
    def mix(self) -> None: ...
    @property
    def jinja_env(self) -> Environment: ...
    @property
    def sources(self) -> tuple[Markup, ...] | None: ...
    @property
    def rendered_sources(self) -> str: ...
    @property
    def limit(self) -> Callable[..., Any]: ...
